networks:
  vision-service-node:
  vision-ethereum:
    name: vision-ethereum-${STACK_IDENTIFIER}-${ETHEREUM_NETWORK-1}
    external: true

services:
  app:
    networks:
      vision-service-node:
      vision-ethereum:
    entrypoint: sh -c 'set -a; . /etc/vision/eth-data/ETHEREUM.env && . /etc/vision/bnb-data/BNB_CHAIN.env; set +a; exec /usr/bin/vision-service-node-server'
    environment:
      VISION_ENV_FILE: /etc/vision/service-node-config.env
      APP_URL: http://localhost:808${INSTANCE-1}
      BNB_CHAIN_PRIVATE_KEY: /etc/vision/bnb-data/keystore
      ETHEREUM_PRIVATE_KEY: /etc/vision/eth-data/keystore
    healthcheck:
      test: ["CMD-SHELL", "set -a; . /etc/vision/eth-data/ETHEREUM.env && . /etc/vision/bnb-data/BNB_CHAIN.env; set +a; exec /usr/bin/vision-service-node-server --status"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - type: volume
        source: bnb-data
        target: /etc/vision/bnb-data
        read_only: true
      - type: volume
        source: eth-data
        target: /etc/vision/eth-data
        read_only: true
      - type: bind
        source: ./signer_key.pem
        target: /etc/vision/service-node-signer.pem
        read_only: true
      - type: bind
        source: ./service-node-config.docker.env
        target: /etc/vision/service-node-config.env
        read_only: true
    develop:
      watch:
        - action: sync+restart
          path: service-node-config.docker.env
          target: /root/service-node-config.docker.env

  worker:
    networks:
      vision-service-node:
      vision-ethereum:
    entrypoint: sh -c 'set -a; . /etc/vision/eth-data/ETHEREUM.env && . /etc/vision/bnb-data/BNB_CHAIN.env; set +a; exec /usr/bin/vision-service-node-celery'
    environment:
      VISION_ENV_FILE: /etc/vision/service-node-config.env
      APP_URL: http://localhost:808${INSTANCE-1}
      BNB_CHAIN_PRIVATE_KEY: /etc/vision/bnb-data/keystore
      ETHEREUM_PRIVATE_KEY: /etc/vision/eth-data/keystore
      VISION_STATUS_MONITOR: 1
    healthcheck:
      test: ["CMD-SHELL", "set -a; . /etc/vision/eth-data/ETHEREUM.env && . /etc/vision/bnb-data/BNB_CHAIN.env; set +a; exec /usr/bin/vision-service-node-celery --status"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - 555${INSTANCE-0}:5555
    volumes:
      - type: volume
        source: bnb-data
        target: /etc/vision/bnb-data
        read_only: true
      - type: volume
        source: eth-data
        target: /etc/vision/eth-data
        read_only: true
      - type: bind
        source: ./signer_key.pem
        target: /etc/vision/service-node-signer.pem
        read_only: true
      - type: bind
        source: ./service-node-config.docker.env
        target: /etc/vision/service-node-config.env
        read_only: true
    develop:
      watch:
        - action: sync+restart
          path: service-node-config.docker.env
          target: /root/service-node-config.docker.env

volumes:
  bnb-data:
    # Requires the same amount of instances as the servicenode
    name: bnb-data-${STACK_IDENTIFIER}-${ETHEREUM_NETWORK-1}
    external: true
  eth-data:
    name: eth-data-${STACK_IDENTIFIER}-${ETHEREUM_NETWORK-1}
    external: true
